In [21]:
import pandas as pd
import numpy as np

In [2]:
path = "/content/Iris.csv"

In [5]:
iris = pd.read_csv(path)

In [9]:
iris.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [11]:
iris.Id.describe()

count    150.000000
mean      75.500000
std       43.445368
min        1.000000
25%       38.250000
50%       75.500000
75%      112.750000
max      150.000000
Name: Id, dtype: float64

In [14]:
iris.Id.count()

150

In [17]:
iris.Id.value_counts()

Id
1      1
95     1
97     1
98     1
99     1
      ..
51     1
52     1
53     1
54     1
150    1
Name: count, Length: 150, dtype: int64

In [18]:
iris.Id.unique()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150])

In [19]:
iris.Species.unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [22]:
df = pd.DataFrame(
    [
        [2.4, np.nan],
        [6.3, -3.4],
        [np.nan, np.nan],
        [0.75, -1.3]
    ],
    index=  ["a", "b", "c", "d"],
    columns=["one", "two"]
)

In [23]:
df

    one  two
a  2.40  NaN
b  6.30 -3.4
c   NaN  NaN
d  0.75 -1.3

In [24]:
df.sum()

one    9.45
two   -4.70
dtype: float64

In [25]:
df.sum(axis = 1)

a    2.40
b    2.90
c    0.00
d   -0.55
dtype: float64

In [26]:
df.sum(axis = 0)

one    9.45
two   -4.70
dtype: float64

In [27]:
df.sum(axis = 2)

ValueError: No axis named 2 for object type DataFrame

In [31]:
df = pd.DataFrame(np.arange(16).reshape(4, 4), columns = ["one", "two", "three", "four"], index = ["London", "Berlin", "Paris", "Istanbul"])

In [32]:
df

          one  two  three  four
London      0    1      2     3
Berlin      4    5      6     7
Paris       8    9     10    11
Istanbul   12   13     14    15

In [36]:
df[["one", "two"]]

          one  two
London      0    1
Berlin      4    5
Paris       8    9
Istanbul   12   13

In [37]:
df[:3]

        one  two  three  four
London    0    1      2     3
Berlin    4    5      6     7
Paris     8    9     10    11

In [39]:
df[df["four"] > 5]

          one  two  three  four
Berlin      4    5      6     7
Paris       8    9     10    11
Istanbul   12   13     14    15

In [40]:
df[df["four"] < 5]

        one  two  three  four
London    0    1      2     3

In [41]:
df.iloc[1]

one      4
two      5
three    6
four     7
Name: Berlin, dtype: int64

In [45]:
df.iloc[1, [1, 2, 3]]

two      5
three    6
four     7
Name: Berlin, dtype: int64

In [46]:
df.iloc[2, [1,  3]]

two      9
four    11
Name: Paris, dtype: int64

In [50]:
df.iloc[[1, 3], [1, 2, 3]]

          two  three  four
Berlin      5      6     7
Istanbul   13     14    15

In [51]:
df.iloc[[1, 2, 3], [1, 2, 3]]

          two  three  four
Berlin      5      6     7
Paris       9     10    11
Istanbul   13     14    15

In [52]:
df.iloc[[0, 2, 3], [1, 3]]

          two  four
London      1     3
Paris       9    11
Istanbul   13    15

In [56]:
df.loc["Paris", ["one", "two"]]

one    8
two    9
Name: Paris, dtype: int64

In [57]:
path = "/content/House_Rent_Dataset.csv"

In [84]:
rent = pd.read_csv(path)

In [62]:
rent.columns

Index(['Posted On', 'BHK', 'Rent', 'Size', 'Floor', 'Area Type',
       'Area Locality', 'City', 'Furnishing Status', 'Tenant Preferred',
       'Bathroom', 'Point of Contact'],
      dtype='object')

In [82]:
temp_df = rent._append(rent)

In [65]:
temp_df

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
0,2022-05-18,2,10000,1100,Ground out of 2,Super Area,Bandel,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner
1,2022-05-13,2,20000,800,1 out of 3,Super Area,"Phool Bagan, Kankurgachi",Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
2,2022-05-16,2,17000,1000,1 out of 3,Super Area,Salt Lake City Sector 2,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
3,2022-07-04,2,10000,800,1 out of 2,Super Area,Dumdum Park,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner
4,2022-05-09,2,7500,850,1 out of 2,Carpet Area,South Dum Dum,Kolkata,Unfurnished,Bachelors,1,Contact Owner
...,...,...,...,...,...,...,...,...,...,...,...,...
4741,2022-05-18,2,15000,1000,3 out of 5,Carpet Area,Bandam Kommu,Hyderabad,Semi-Furnished,Bachelors/Family,2,Contact Owner
4742,2022-05-15,3,29000,2000,1 out of 4,Super Area,"Manikonda, Hyderabad",Hyderabad,Semi-Furnished,Bachelors/Family,3,Contact Owner
4743,2022-07-10,3,35000,1750,3 out of 5,Carpet Area,"Himayath Nagar, NH 7",Hyderabad,Semi-Furnished,Bachelors/Family,3,Contact Agent
4744,2022-07-06,3,45000,1500,23 out of 34,Carpet Area,Gachibowli,Hyderabad,Semi-Furnished,Family,2,Contact Agent
4745,2022-05-04,2,15000,1000,4 out of 5,Carpet Area,Suchitra Circle,Hyderabad,Unfurnished,Bachelors,2,Contact Owner

In [67]:
rent.count()

Posted On            4746
BHK                  4746
Rent                 4746
Size                 4746
Floor                4746
Area Type            4746
Area Locality        4746
City                 4746
Furnishing Status    4746
Tenant Preferred     4746
Bathroom             4746
Point of Contact     4746
dtype: int64

In [68]:
temp_df.count()

Posted On            9492
BHK                  9492
Rent                 9492
Size                 9492
Floor                9492
Area Type            9492
Area Locality        9492
City                 9492
Furnishing Status    9492
Tenant Preferred     9492
Bathroom             9492
Point of Contact     9492
dtype: int64

In [69]:
print(rent.shape)
print(temp_df.shape)

(4746, 12)
(9492, 12)

In [78]:
temp_df.drop_duplicates()
temp_df.shape

(4746, 12)

In [79]:
temp_df.drop_duplicates(inplace = True) # saving in variable
temp_df.shape

(4746, 12)

In [83]:
temp_df.drop_duplicates(inplace = True, keep = "last")
temp_df.shape

(4746, 12)

In [86]:
temp_df.drop_duplicates(inplace = True, keep = "first")
temp_df.shape

(4746, 12)

In [89]:
temp_df.columns

Index(['Posted On', 'BHK', 'Rent', 'Size', 'Floor', 'Area Type',
       'Area Locality', 'City', 'Furnishing Status', 'Tenant Preferred',
       'Bathroom', 'Point of Contact'],
      dtype='object')

In [92]:
temp_df.rename(columns = {"BHK": "AI", "Area Locality":"Location"}, inplace = True)

In [93]:
temp_df.columns

Index(['Posted On', 'AI', 'Rent', 'Size', 'Floor', 'Area Type', 'Location',
       'City', 'Furnishing Status', 'Tenant Preferred', 'Bathroom',
       'Point of Contact'],
      dtype='object')

In [94]:
temp_df.columns = [col.lower() for col in temp_df]

In [95]:
temp_df.columns

Index(['posted on', 'ai', 'rent', 'size', 'floor', 'area type', 'location',
       'city', 'furnishing status', 'tenant preferred', 'bathroom',
       'point of contact'],
      dtype='object')

In [102]:
path = "/content/HouseRent.csv"

In [103]:
rent = pd.read_csv(path)

In [104]:
rent

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
0,2022-05-18,2,10000.0,1100.0,Ground out of 2,Super Area,Bandel,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner
1,2022-05-13,2,20000.0,800.0,1 out of 3,Super Area,"Phool Bagan, Kankurgachi",Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
2,2022-05-16,2,17000.0,1000.0,1 out of 3,Super Area,Salt Lake City Sector 2,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
3,2022-07-04,2,10000.0,800.0,1 out of 2,Super Area,Dumdum Park,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner
4,2022-05-09,2,7500.0,850.0,1 out of 2,Carpet Area,South Dum Dum,Kolkata,Unfurnished,Bachelors,1,Contact Owner
...,...,...,...,...,...,...,...,...,...,...,...,...
4741,2022-05-18,2,15000.0,1000.0,3 out of 5,Carpet Area,Bandam Kommu,Hyderabad,Semi-Furnished,Bachelors/Family,2,Contact Owner
4742,2022-05-15,3,29000.0,2000.0,1 out of 4,Super Area,"Manikonda, Hyderabad",Hyderabad,Semi-Furnished,Bachelors/Family,3,Contact Owner
4743,2022-07-10,3,35000.0,1750.0,3 out of 5,Carpet Area,"Himayath Nagar, NH 7",Hyderabad,Semi-Furnished,Bachelors/Family,3,Contact Agent
4744,2022-07-06,3,45000.0,1500.0,23 out of 34,Carpet Area,Gachibowli,Hyderabad,Semi-Furnished,Family,2,Contact Agent
4745,2022-05-04,2,15000.0,1000.0,4 out of 5,Carpet Area,Suchitra Circle,Hyderabad,Unfurnished,Bachelors,2,Contact Owner

In [105]:
temp_df = rent.copy()

In [106]:
temp_df.isnull( ).sum()

Posted On            0
BHK                  0
Rent                 2
Size                 1
Floor                0
Area Type            0
Area Locality        1
City                 0
Furnishing Status    0
Tenant Preferred     0
Bathroom             0
Point of Contact     0
dtype: int64

In [107]:
temp2 = temp_df.dropna()

In [108]:
print(temp2.shape)
print(temp_df.shape)

(4742, 12)
(4746, 12)

In [110]:
rent_mean = rent.Rent.mean()

In [111]:
rent_mean

34994.71332209106